[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  FastLED
  me-no-dev/WebSockets@^2.3.5
  bblanchon/ArduinoJson@^6.21.0

[env:esp32c3dev]
platform = espressif32
board = esp32c3-dev
framework = arduino
monitor_speed = 115200
lib_deps =
  FastLED
  me-no-dev/WebSockets@^2.3.5
  bblanchon/ArduinoJson@^6.21.0

; Uncomment / add board entries for your exact hardware (e.g. esp32groom-32)
